language: swift
osx_image: xcode10.2

before_install:
  - gem install cocoapods -v '1.7.2'
  - cd StantUiIosLibraryDemo
  - pod install

script:
    - xcodebuild -workspace StantUiIosLibraryDemo.xcworkspace -scheme StantUiIosLibraryDemoTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.4' test ONLY_ACTIVE_ARCH=NO
