language: swift
cache:
  bundler:   true
  cocoapods: true
  timeout:   1000
osx_image: xcode11.5

before_install:
  - gem install cocoapods -v '1.7.2'
  - cd StantUiIosLibraryDemo
  - pod install

script:
  - xcodebuild -workspace StantUiIosLibraryDemo.xcworkspace -scheme StantUiIosLibraryDemoTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.5' test ONLY_ACTIVE_ARCH=YES
