language: swift
osx_image: xcode11.3.1

before_install:
  - gem install cocoapods -v '1.7.2'
  - cd StantUiIosLibraryDemo
  - pod install

script:
  - xcodebuild -workspace StantUiIosLibraryDemo.xcworkspace -scheme StantUiIosLibraryDemoTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XR,OS=13.3' test ONLY_ACTIVE_ARCH=NO
