language: swift
osx_image: xcode10.2

before_install:
  - gem install cocoapods -v '1.7.2'
  - cd StantUiIosLibraryDemo
  - pod install

script:
  - travis_retry  xcodebuild -workspace StantUiIosLibraryDemo.xcworkspace -scheme StantUiIosLibraryDemoTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.2' test ONLY_ACTIVE_ARCH=NO
