#use_frameworks!

source 'https://github.com/stantmob/stant-ui-ios-library.git'

target 'StantUiIosLibrary_Example' do
  pod 'StantUiIosLibrary', :path => '../'

  target 'StantUiIosLibrary_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
